version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/my-resume
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}

      # Run installation
      - run:
          name: Installing dependencies
          command: npm install
      
      - checkout

      - save_cache:
          paths: node_modules
          key: dependencies-{{ checksum "package.json" }}

      # run build!
      - run:
          name: Build React App
          command: |
            npm run build

      # run build!
      - run:
          name: Export React App
          command: |
            npm run export

  test:
    working_directory: ~/my-resume
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Installing deps
          command: npm install

      - checkout

      - save_cache:
          paths: node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Run ESLint
          command: npm test

  deploy:
    working_directory: ~/my-resume
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout

      - run:
          name: Deploying App
          command: npm run deploy

workflows:
  version: 2
  test-build:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master