version: 2
jobs:
  Build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/my-resume
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}

      # Run installation
      - run:
          name: Installing dependencies
          command: npm install
      
      - checkout

      - save_cache:
          paths: node_modules
          key: dependencies-{{ checksum "package.json" }}

      # run build!
      - run:
          name: Build React App
          command: |
            npm run build

      # run build!
      - run:
          name: Export React App
          command: |
            npm run export

  Test:
    working_directory: ~/my-resume
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Installing deps
          command: npm install

      - checkout

      - save_cache:
          paths: node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Run ESLint
          command: npm test

workflows:
  version: 2
  Test_Build:
    jobs:
      - test
      - Build:
          requires:
            - Test
